---
# tasks file for common
- name: Update all packages
  apt:
    name: '*'
    state: latest
  become: yes

- name: Install NTP, git and EPEL
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - git
    - epel-release
  become: yes

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf 
  notify: Restart NTP
  become: yes
  
- name: insert iptables template
  template: 
    src: iptables.j2 
    dest: /etc/sysconfig/iptables
  notify: restart iptables
  become: yes
  